# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_label = QtWidgets.QLabel(self.centralwidget)
        self.Image_label.setGeometry(QtCore.QRect(10, 10, 441, 391))
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(36)
        self.Image_label.setFont(font)
        self.Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_label.setObjectName("Image_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 424, 181, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenfile = QtWidgets.QAction(MainWindow)
        self.actionOpenfile.setObjectName("actionOpenfile")
        self.actionClosePlatform = QtWidgets.QAction(MainWindow)
        self.actionClosePlatform.setObjectName("actionClosePlatform")
        self.menuMenu.addAction(self.actionOpenfile)
        self.menuMenu.addAction(self.actionClosePlatform)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "影像處理平台"))
        self.Image_label.setText(_translate("MainWindow", "No Image"))
        self.pushButton.setText(_translate("MainWindow", "馬賽克"))
        self.pushButton_2.setText(_translate("MainWindow", "選取影像區域"))
        self.menuMenu.setTitle(_translate("MainWindow", "選單"))
        self.actionOpenfile.setText(_translate("MainWindow", "開啟影像"))
        self.actionClosePlatform.setText(_translate("MainWindow", "關閉平台"))
